# Generated by Django 5.0.6 on 2024-06-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
