# Generated by Django 5.0.6 on 2024-06-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kgx_app', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=100)),
                ('email_p', models.EmailField(max_length=254)),
                ('email_clg', models.EmailField(max_length=254)),
                ('phn_no', models.IntegerField()),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('hackathon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('date', models.DateField()),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgx_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgx_app.profile')),
            ],
        ),
    ]
