# Generated by Django 5.1 on 2024-08-20 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0005_internship_learnbypractice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Submitted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='department',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='entry_time',
            field=models.TimeField(verbose_name='Entry Time'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='exit_time',
            field=models.TimeField(verbose_name='Exit Time'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Holiday Name'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='purpose',
            field=models.CharField(max_length=200, verbose_name='Purpose of Holiday'),
        ),
    ]
