# Generated by Django 5.1 on 2024-08-20 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0006_remove_holiday_date_remove_holiday_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
