# Generated by Django 5.0.6 on 2024-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnbypractice',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
