# Generated by Django 5.1 on 2024-08-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0010_learnbypractice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnbypractice',
            name='description',
        ),
    ]
