# Generated by Django 5.1 on 2024-10-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hackathon',
        ),
    ]
