# Generated by Django 5.0.6 on 2024-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0014_profile_role_alter_profile_phn_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifi',
            old_name='mac',
            new_name='mac_address',
        ),
        migrations.AddField(
            model_name='wifi',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='wifi_screenshots/'),
        ),
        migrations.AddField(
            model_name='wifi',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
