# Generated by Django 5.1 on 2024-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0015_rename_mac_wifi_mac_address_wifi_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('reference_link', models.URLField(blank=True, null=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
