# Generated by Django 5.1 on 2024-10-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgx_app', '0017_inprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('reference_link', models.URLField(blank=True, null=True)),
                ('task_link', models.URLField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
